export const ADD_CITY = 'ADD_CITY';
export const DELETE_CITY = 'DELETE_CITY';
export const RESTORE_LAST_DELETED_CITY = 'RESTORE_LAST_DELETED_CITY';
export const FETCH_CITY_SUGGESTIONS = 'FETCH_CITY_SUGGESTIONS';