export const ADD_CITY = 'ADD_CITY';
export const DELETE_CITY = 'DELETE_CITY';
export const RESTORE_LAST_DELETED_CITY = 'RESTORE_LAST_DELETED_CITY';
export const REQUEST_CITY_SUGGESTIONS = 'REQUEST_CITY_SUGGESTIONS';
export const RECEIVE_CITY_SUGGESTIONS = 'RECEIVE_CITY_SUGGESTIONS';