export const ADD_CITY = 'ADD_CITY';
export const DELETE_CITY = 'DELETE_CITY';
export const RESTORE_DELETED_CITY = 'RESTORE_DELETED_CITY';
export const CACHE_DELETED_CITY = 'CACHE_DELETED_CITY';
// TODO: CLEAR_DELETED_CITY?
export const CHANGE_NOTIFICATION_TEXT = 'CHANGE_NOTIFICATION_TEXT';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const REQUEST_CITY_SUGGESTIONS = 'REQUEST_CITY_SUGGESTIONS';
export const RECEIVE_CITY_SUGGESTIONS = 'RECEIVE_CITY_SUGGESTIONS';